"""verify_R001.py — gate harness for report R001.

A gate is a machine-checkable assertion about this report's own outputs
(analysis/results/), regenerated by analysis/run_all.jl from the FROZEN sources
in deps/. The report quotes these gate results; the gates are what make the
quoting honest.

POLARITY WARNING (read before acting on a failure).
Gates whose name contains `bug_present` assert that a DEFECT IS STILL THERE in
the frozen deps/ snapshot. They pass today because the bug exists. Once F1/F2/F3
are fixed in the live tree and deps/ is re-frozen, these gates SHOULD FLIP TO
FAIL — that flip is the evidence the fix landed, not a regression. Every other
gate is an ordinary correctness gate and a failure means something broke.

Run: python analysis/verify_R001.py     (exit code 1 if any gate fails)
"""
from __future__ import annotations
import hashlib
import json
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
DEPS = HERE.parent / "deps"
for _p in (str(DEPS), str(HERE)):          # deps/ FIRST: frozen code wins
    if _p not in sys.path:
        sys.path.insert(0, _p)

RES = HERE / "results"
GATES = {}


def gate(name, ok, detail=""):
    GATES[name] = {"pass": bool(ok), "detail": str(detail)}
    print(f"{'PASS' if ok else 'FAIL'}  {name}  {detail}")


def jload(name):
    return json.loads((RES / name).read_text())


def main():
    rhs = jload("rhs_and_bugs.json")
    meta = jload("data_summary.json")
    stiff = pd.read_csv(RES / "stiff_branch.csv")
    sweep = pd.read_csv(RES / "sweep.csv")
    sanity = pd.read_csv(RES / "loss_sanity.csv")
    smeta = jload("sweep_meta.json")

    # --- G1  FROZEN SNAPSHOT MATCHES deps/MANIFEST.md ---------------------
    man = (DEPS / "MANIFEST.md").read_text()
    ok, det = True, []
    for f in sorted(DEPS.glob("*.jl")):
        h = hashlib.sha256(f.read_bytes()).hexdigest()
        hit = f"`{h}`" in man
        ok &= hit
        det.append(f"{f.name}:{'ok' if hit else 'DRIFTED'}")
    gate("G1_deps_frozen_matches_manifest", ok, "; ".join(det))

    # --- G2  MATHEMATICAL IDENTITY: odefun_poly! == odefun ----------------
    d = rhs["A_odefun_poly_maxabsdiff"]
    gate("G2_odefun_poly_equals_odefun", d < 1e-12,
         f"max|odefun - odefun_poly!| over 200 random states = {d:.3e} (tol 1e-12)")

    # --- G3  F1 bug_present: odefun_new IS the linear truncation ----------
    same_lin = max(abs(a - b) for a, b in
                   zip(rhs["B_odefun_new"], rhs["B_linear_truncation"])) < 1e-12
    diff_true = max(abs(a - b) for a, b in
                    zip(rhs["B_odefun_new"], rhs["B_odefun_true"])) > 1e-6
    gate("G3_F1_bug_present_odefun_new_is_linear_truncation", same_lin and diff_true,
         f"odefun_new={rhs['B_odefun_new']} == linear_truncation, "
         f"!= true RHS {rhs['B_odefun_true']}")

    # --- G4  F1 bug_present: the Jacobian (1,1) entry has the WRONG SIGN --
    j_new, j_true = rhs["B_jac_odefun_new"], rhs["B_jac_true"]
    gate("G4_F1_bug_present_jacobian_j11_sign_flipped",
         j_new[0] > 0 > j_true[0],
         f"J11 odefun_new={j_new[0]} (>0) vs true={j_true[0]} (<0); "
         f"off-diagonals agree: {j_new[1:]==j_true[1:]}")

    # --- G5  F2 bug_present: stiff branch drops the w-residual ------------
    ok = bool((stiff.missing_fraction > 0.10).all() and (stiff.missing_fraction < 0.20).all())
    gate("G5_F2_bug_present_stiff_drops_w_residual", ok,
         "missing fraction per window_size: " +
         ", ".join(f"k={int(r.window_size)}:{100*r.missing_fraction:.1f}%"
                   for r in stiff.itertuples()))

    # --- G6  SOLVER IDENTITY: repaired stiff branch == explicit branch ----
    worst = float(stiff.repaired_minus_explicit.max())
    gate("G6_repaired_stiff_matches_explicit", worst < 1e-8,
         f"max |repaired - explicit| = {worst:.3e} (tol 1e-8) — the two "
         f"integrators agree once the dropped continuation is restored")

    # --- G7  F3 bug_present: mod 8 raises the two documented errors -------
    ok = (rhs["C_mod8_fhn_u0_error"] == "UndefVarError"
          and rhs["D_mod8_fsl_error"] == "BoundsError"
          and rhs["D2_mod8_fsl_reads_global_data"] is True)
    gate("G7_F3_bug_present_mod8_runtime_errors", ok,
         f"fhn_u0 -> {rhs['C_mod8_fhn_u0_error']}; "
         f"forward_simulation_loss -> {rhs['D_mod8_fsl_error']}; "
         f"reads global `data` -> {rhs['D2_mod8_fsl_reads_global_data']}")

    # --- G8  REPRODUCTION TABLE: section 5 values as published ------------
    published = {   # (arm, window_size): (J, p_err) exactly as the report prints
        ("guess_propagation", 1):   (0.01338, 1.1347),
        ("guess_propagation", 2):   (0.01360, 0.3967),
        ("guess_propagation", 5):   (0.01316, 0.1563),
        ("guess_propagation", 10):  (0.01055, 0.1851),
        ("guess_propagation", 25):  (0.00991, 0.2414),
        ("guess_propagation", 50):  (0.00977, 0.2717),
        ("guess_propagation", 100): (0.00960, 0.2835),
        ("no_propagation", 1):      (0.01338, 1.1347),
        ("no_propagation", 2):      (0.01608, 1.0868),
        ("no_propagation", 5):      (0.04694, 1.8765),
        ("no_propagation", 10):     (1000.0,  1.5679),
        ("no_propagation", 25):     (1000.0,  1.5679),
        ("no_propagation", 50):     (1000.0,  1.5679),
        ("no_propagation", 100):    (1000.0,  1.5679),
    }
    idx = sweep.set_index(["arm", "window_size"])
    ok, det = True, []
    for key, (jref, pref) in published.items():
        row = idx.loc[key]
        dj, dp = abs(row.J - jref), abs(row.p_err - pref)
        cell_ok = dj <= 5e-5 * max(1.0, abs(jref)) and dp <= 5e-5
        ok &= cell_ok
        if not cell_ok:
            det.append(f"{key}: dJ={dj:.2e} dp={dp:.2e}")
    gate("G8_section5_table_reproduces", ok,
         "all 14 cells match the printed values to 5e-5"
         if ok else "; ".join(det))

    # --- G9  CONTROL ARM HITS THE BLOW-UP PLATEAU AND KEEPS THE SEED ------
    #  Cellwise, not aggregate: every no_propagation row with k>=10 must be
    #  exactly the penalty AND carry the untouched seed error.
    seed_err = smeta["seed_p_err"]
    sub = sweep[(sweep.arm == "no_propagation") & (sweep.window_size >= 10)]
    ok = bool((sub.J == smeta["blowup_penalty"]).all()
              and (abs(sub.p_err - seed_err) < 1e-12).all()
              and len(sub) == 4)
    gate("G9_control_arm_is_plateau_not_a_fit", ok,
         f"{len(sub)} rows with k>=10: J == {smeta['blowup_penalty']} and "
         f"p_err == seed ({seed_err:.4f}) — the reported minimiser is the seed")

    # --- G10 GUESS PROPAGATION BEATS THE CONTROL, CELLWISE ----------------
    gp = sweep[sweep.arm == "guess_propagation"].set_index("window_size")
    npz = sweep[sweep.arm == "no_propagation"].set_index("window_size")
    strictly = [k for k in gp.index if k > 1 and gp.loc[k, "p_err"] < npz.loc[k, "p_err"]]
    tied = [k for k in gp.index if abs(gp.loc[k, "p_err"] - npz.loc[k, "p_err"]) < 1e-12]
    ok = len(strictly) == 6 and tied == [1]
    gate("G10_propagation_better_cellwise", ok,
         f"strictly better at k={strictly}; tied at k={tied} (k=1 is the same "
         f"problem from the same seed, so a tie there is required)")

    # --- G11 NON-MONOTONE PARAMETER ERROR (the report's caveat) -----------
    pe = gp["p_err"]
    argmin_k = int(pe.idxmin())
    ok = argmin_k not in (int(pe.index.min()), int(pe.index.max())) and \
        pe.loc[100] > pe.loc[argmin_k]
    gate("G11_p_err_non_monotone_in_window_size", ok,
         f"min ||p-p*|| = {pe.min():.4f} at k={argmin_k}, rising to "
         f"{pe.loc[100]:.4f} at k=100 while J falls to {gp.loc[100,'J']:.5f}")

    # --- G12 COST DISCRIMINATES: J(p*) << J(random p), cellwise -----------
    ok = bool((sanity.J_true < sanity.J_random_min).all())
    gate("G12_cost_discriminates", ok,
         f"J(p*) in [{sanity.J_true.min():.4f}, {sanity.J_true.max():.4f}]; "
         f"J(random p) over {int(sanity.n_random_draws.iloc[0])} draws in "
         f"[{sanity.J_random_min.min():.4f}, {sanity.J_random_max.max():.1f}]")

    # --- G13 AD PATH IS FINITE -------------------------------------------
    gate("G13_forwarddiff_through_windowed_loss",
         bool(meta["grad_all_finite"]) and meta["grad_norm_at_ptrue_ws5"] > 0,
         f"||grad J|| at p*, k=5 = {meta['grad_norm_at_ptrue_ws5']:.5f}, all finite")

    # --- G14 COMPLETENESS + HASH LEDGER ----------------------------------
    ok, det, hashes = True, [], {}
    for p in sorted(list(RES.glob("*.csv")) + list(RES.glob("*.json"))):
        if p.name in ("results_hashes.json", "gates_summary.json"):
            continue
        hashes[p.name] = hashlib.sha256(p.read_bytes()).hexdigest()
        det.append(p.name)
    ok &= len(hashes) >= 6
    (RES / "results_hashes.json").write_text(json.dumps(hashes, indent=1))
    gate("G14_completeness_hashes", ok, f"{len(hashes)} files: " + ", ".join(det))

    (RES / "gates_summary.json").write_text(json.dumps(GATES, indent=1))
    n_fail = sum(1 for g in GATES.values() if not g["pass"])
    print(f"\n{len(GATES)} gates, "
          f"{'ALL PASS' if n_fail == 0 else f'{n_fail} FAIL'}")
    sys.exit(1 if n_fail else 0)


if __name__ == "__main__":
    main()
