#!/usr/bin/env python
"""make_report_md.py — derive report.md (full-content Markdown rendition) from report.tex.

report.tex is authoritative. This script: (1) inlines every `\input{tables/X}` with tables/X.md
(the Markdown twin written by make_tables.py) and tables/gates_status.tex, (2) converts figure
environments to Markdown images with their full captions, (3) runs pandoc latex→gfm for the rest,
(4) post-processes so that math stays real LaTeX inside $…$. Re-run whenever report.tex changes.
"""
import re, subprocess, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
tex = (ROOT / "report.tex").read_text()
# 1. tables
def inline_table(m):
    name = m.group(1)
    md = ROOT / "tables" / f"{name}.md"
    if md.exists(): return "\n\nTABLEBLOCK" + name + "TABLEBLOCK\n\n"
    t = ROOT / "tables" / f"{name}.tex"
    return t.read_text().strip() if t.exists() else ""
tex = re.sub(r"\\input\{tables/([^}]+)\}", inline_table, tex)
# 1b. the front longtable -> pipe table (pandoc would emit HTML because of the \multicolumn rows)
def cell(x):
    x = re.sub(r"\\ref\{fig:(\d+)\}", lambda m: f"Figure {int(m.group(1))}", x)
    x = re.sub(r"\\texttt\{([^}]*)\}", lambda m: "`" + m.group(1).replace("\\_", "_") + "`", x)
    x = re.sub(r"\\emph\{([^}]*)\}", r"*\1*", x)
    return x.replace("\\,", " ").replace("\\%", "%").replace("---", "—").replace("--", "–").replace("~", " ").strip()
def longtable(m):
    body = m.group(1)
    body = re.sub(r"\\(toprule|midrule|bottomrule|endhead)", "", body)
    rows = [r.strip() for r in body.split("\\\\") if r.strip()]
    out = ["| Figure | What is plotted | What it demonstrates / how to use it on a slide |", "|---|---|---|"]
    for r in rows[1:]:   # first row is the header
        mm = re.match(r"\\multicolumn\{3\}\{l\}\{(.*)\}", r, re.S)
        if mm: out.append("| " + cell(mm.group(1)) + " | | |"); continue
        cells = [cell(c) for c in r.split("&")]
        if len(cells) == 3: out.append("| " + " | ".join(cells) + " |")
    LONGTABLES.append("\n".join(out)); return "\n\nLONGTABLEBLOCK\n\n"
LONGTABLES = []
tex = re.sub(r"\\begin\{longtable\}\{[^}]*\}(.*?)\\end\{longtable\}", longtable, tex, flags=re.S)
tex = tex.replace("\\small\n", "").replace("\\normalsize\n", "")
# 2. figures -> placeholder with path + caption (keep caption LaTeX for pandoc)
def fig(m):
    body = m.group(1)
    path = re.search(r"\\includegraphics\[[^\]]*\]\{([^}]+)\}", body).group(1)
    cap = re.search(r"\\caption\{(.*)\}\\label\{([^}]+)\}", body, re.S)
    caption, label = cap.group(1), cap.group(2)
    return f"\n\nFIGBLOCK{path}FIGSEP{label}FIGSEP{caption}FIGBLOCK\n\n"
tex = re.sub(r"\\begin\{figure\}\[H\](.*?)\\end\{figure\}", fig, tex, flags=re.S)
tex = re.sub(r"\\begin\{table\}\[H\](.*?)\\end\{table\}", lambda m: "\n\n" + re.sub(r"\\centering|\\scriptsize|\\small", "", m.group(1)), tex, flags=re.S)
tex = tex.replace("\\tableofcontents", "").replace("\\addcontentsline{toc}{section}{Table of figures}", "").replace("\\addcontentsline{toc}{section}{Reproduction}", "")
tex = re.sub(r"\\readthis\{", r"\\textbf{Read this:} {", tex)
tex = re.sub(r"\\fig\{([^}]+)\}", r"`figures/\1`", tex)
tex = re.sub(r"\\pathtt\{([^}]+)\}", r"\\texttt{\1}", tex)
tmp = ROOT / "analysis" / "_report_tmp.tex"; tmp.write_text(tex)
md = subprocess.run(["pandoc", "-f", "latex", "-t", "gfm+tex_math_dollars", "--wrap=none", str(tmp)], capture_output=True, text=True, check=True).stdout
tmp.unlink()
# 3. resolve placeholders
figcount = [0]
def figmd(m):
    path, label, caption = m.group(1), m.group(2), m.group(3)
    figcount[0] += 1
    return f"**Figure {figcount[0]}** (`{path}`)\n\n![{label}]({path.replace('.pdf', '.png')})\n\n*{caption.strip()}*\n"
md = re.sub(r"FIGBLOCK(.*?)FIGSEP(.*?)FIGSEP(.*?)FIGBLOCK", figmd, md, flags=re.S)
for t in LONGTABLES: md = md.replace("LONGTABLEBLOCK", t, 1)
md = re.sub(r"TABLEBLOCK(.*?)TABLEBLOCK", lambda m: (ROOT / "tables" / f"{m.group(1)}.md").read_text().strip(), md)
# figure references \ref{fig:NN} come out as "[fig:NN]" — turn into "Figure NN"
md = re.sub(r"\[?\\?\[fig:(\d+)\]\]?", lambda m: f"Figure {int(m.group(1))}", md)
md = re.sub(r"\[tab:T(\d)\]", r"Table T\1", md).replace("[sec:", "(section: ").replace("(section: gates]", "(Gates)").replace("(section: bugs]", "(Part G)").replace("(section: gp]", "(Part D)")
header = ("# R002 — Figure atlas: multiple shooting with guess propagation for sparse model selection\n\n"
          "**Report ID:** R002 (`reports/2026-09-11-R002-multishooting-figure-atlas/`)  \n**Date:** 11 September 2026  \n"
          "**Authoritative source:** `report.tex` / `report.pdf` — this `.md` is a derived, full-content view generated by `analysis/make_report_md.py`; on disagreement the `.tex` wins.  \n"
          f"**Gates:** {(ROOT / 'tables' / 'gates_status.tex').read_text().strip()} — `analysis/results/gates_summary.json`  \n"
          "**Animation:** `figures/anim_sweep.gif`\n\n")
(ROOT / "report.md").write_text(header + md)
print("report.md:", len(md), "chars;", figcount[0], "figures")
